# Generated by Django 2.2.2 on 2019-07-17 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('test_ws', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification_test',
        ),
    ]
