# Generated by Django 2.1.7 on 2019-07-01 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('from_user', models.ForeignKey(on_delete=None, related_name='message_from_user', to=settings.AUTH_USER_MODEL)),
                ('seen', models.ManyToManyField(related_name='seen', to=settings.AUTH_USER_MODEL)),
                ('to_group', models.ForeignKey(on_delete=None, related_name='to_group', to='chat.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('seen', models.BooleanField()),
                ('from_user', models.ForeignKey(on_delete=None, related_name='notification_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=None, related_name='notification_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
