# Generated by Django 2.2.2 on 2019-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
