# Generated by Django 2.2.2 on 2019-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_user_sign_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
