# Generated by Django 2.2.2 on 2019-07-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_user_sign_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('seen', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
