# Generated by Django 2.2.2 on 2019-07-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190703_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(default='single', max_length=20),
            preserve_default=False,
        ),
    ]
