# Generated by Django 2.2.2 on 2019-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0005_auto_20190717_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('seen', models.BooleanField()),
            ],
        ),
    ]
